import clgui

vertical_layout = clgui.Layouts.VStack()
main = clgui.GUI(layout=vertical_layout)
button_list = clgui.ButtonList()
button_list2 = clgui.ButtonList()
button1 = clgui.Button("Hello", lambda: print("Hello"))
button2 = clgui.Button("World", lambda: print("World"))
button_list.addButtons([button1, button2])
button3 = clgui.Button("Among", lambda: print("Among"))
button4 = clgui.Button("Us", lambda: print("Us"))
button_list2.addButtons([button3, button4])
vertical_layout.add(button_list)
vertical_layout.add(button_list2)
vertical_layout.add(clgui.Button("test", lambda: print("test")))
main.show()